server.port=8080
spring.application.name=bigfile-sftp-backend

spring.datasource.url=jdbc:h2:file:${BIGFILE_SFTP_DB_PATH:./bigfile-sftp-backend/db/bigfile-sftp};AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

camel.springboot.name=bigfile-sftp-camel
camel.springboot.main-run-controller=false

logging.level.org.apache.camel.component.file.remote.SftpOperations=WARN
